apiVersion: v1
kind: Service
metadata:
  name: frontendapp-lb      
spec:
  selector:
    app: frontendapp           # forum-api      
  ports:
  - port: 8090
    targetPort: 80               # 5000
    nodePort: 31000
  type: LoadBalancer