apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: my-postgres
  name: my-postgres
spec:
  replicas: {{ .Values.dbDeployment.replicas }}
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      volumes:
        - name: database-pv
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
      - image: iaotle/my-postgres:latest
        imagePullPolicy: {{ .Values.dbContainer.imagePullPolicy }}
        name: my-postgres
        ports:
        - containerPort: {{ .Values.dbContainer.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.dbContainer.containerMountpath }}
          name: database-pv
        resources: {}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: postgres-secret 
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef: 
              name: postgres-secret 
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef: 
              name: postgres-cm 
              key: POSTGRES_DB
        - name: PGDATA
          value: {{ .Values.dbContainer.containerMountpath }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}