apiVersion: v1
kind: Service
metadata:
  name: frontendapp-lb 
spec:
  selector:
    app: frontendapp           
  ports:
  - port: {{ .Values.frontendappLoadBalancer.port }}
    targetPort: {{ .Values.frontendappLoadBalancer.targetPort }}
  type: LoadBalancer