apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  labels:
    app: frontendapp
spec:
  selector:                         
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
      - name: frontendapp-cont
        image: iaotle/frontendapp:latest
        imagePullPolicy: {{ .Values.frontendappContainer.imagePullPolicy }}      
        ports:
        - containerPort: {{ .Values.frontendappContainer.containerPort }}
        resources:
          limits:
            cpu : 500m
          requests: 
            cpu : 200m    
      restartPolicy: {{ .Values.frontendappContainer.restartPolicy }} 
