apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.dbPVC.accessModes }}
  resources:
    requests:
      storage: {{ .Values.dbPVC.storage }}
