apiVersion: v1
kind: Service
metadata:
  name: rest-lb      
spec:
  selector:
    app: rest-api    
  ports:
  - port: {{ .Values.restLoadbalancer.port }}
    targetPort: {{ .Values.restLoadbalancer.targetPort }}
  type: LoadBalancer