apiVersion: v1 
kind: Secret 
metadata: 
  name: postgres-secret
type: Opaque 
data:
  POSTGRES_USER: {{ .Values.dbSecret.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.dbSecret.POSTGRES_PASSWORD }}