apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-postgres
  name: my-postgres
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{ .Values.dbClusterIP.port }}
    protocol: TCP
    targetPort: {{ .Values.dbClusterIP.targetPort }}
  selector:
    app: my-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}