apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: standard-user-crb
subjects:
- kind: User
  name: standarduser1 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: standard-user-cr
  apiGroup: rbac.authorization.k8s.io
