apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database
  name: database
spec:
  containers:
  - image: postgres
    name: database
    ports:
    - containerPort: 5432
    resources: {}
    env:
    - name: POSTGRES_PASSWORD
      value: "testing"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}