apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
      - image: my-postgres:local
        imagePullPolicy: Never
        name: database
        ports:
        - containerPort: 5432
        resources: {}
        env:
        - name: POSTGRES_PASSWORD
          value: "testing"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}